name: Приклад GitHub Actions зі змінним середовищем

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST2: "some_value"

    steps:
    - name: Клонувати репозиторій
      uses: actions/checkout@v2

    - name: Вивести значення змінної середовища TEST2
      run: |
        echo "Значення змінної середовища TEST2: $TEST2"
